name=input("名字:")
qq=input("qq:")
tele=input("手机号:")
school=input("学校：")
print("=====================================================")
print("名字：", name)
print("QQ:", qq)
print("手机号：", tele)
print("学校：", school)
print("=====================================================")